### ISSUE TITLE
Reboot and install on SGS3.

### ISSUE THREAD

**Issue by Mushishi** [vetruvet/ota-update-centre#6] opened 2012-08-12 21:26 UTC
When OTAUpdater is done downloading the rom, witch works great then the install script it makes for CWM link the file to /storage/sdcard0/OTA-Updater/rom name. Problem is just there is no /storage/sdcard0 and if i do the install manual from the CWM it shows just as /sdcard/OTA-Updater/rom name

It was like that on RC2.

On RC3 it dont even reboot after it have downloaded the rom.

This is the logcat from the reboot. And it do ask for SU access and that is granted.

V/OTAUpdater::Download( 4708): Found old zip, checking md5
V/OTAUpdater::Download( 4708): old zip md5: de44b769d29aad148f561f11cd612436
I/Choreographer( 4708): Skipped 178 frames!  The application may be doing too much work on its main thread.
I/dalvikvm( 4708): Jit: resizing JitTable from 4096 to 8192
D/su      ( 5274): Found file
D/su      ( 5274): this is the last character 101 of the string
D/su      ( 5274): Comparing s /system/bin/sh, 14 to /system/bin/sh
D/su      ( 5274): 10022 com.updater.ota executing 0 /system/bin/sh using shell /system/bin/sh : sh
W/System.err( 4708): java.lang.SecurityException: Neither user 10022 nor current process has android.permission.REBOOT.
W/System.err( 4708):    at android.os.Parcel.readException(Parcel.java:1425)
W/System.err( 4708):    at android.os.Parcel.readException(Parcel.java:1379)
W/System.err( 4708):    at android.os.IPowerManager$Stub$Proxy.reboot(IPowerManager.java:519)
W/System.err( 4708):    at android.os.PowerManager.reboot(PowerManager.java:557)
W/System.err( 4708):    at com.updater.ota.ListFilesActivity$5$1.onClick(ListFilesActivity.java:258)
W/System.err( 4708):    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
W/System.err( 4708):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err( 4708):    at android.os.Looper.loop(Looper.java:137)
W/System.err( 4708):    at android.app.ActivityThread.main(ActivityThread.java:4928)
W/System.err( 4708):    at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 4708):    at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err( 4708):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
W/System.err( 4708):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:558)
W/System.err( 4708):    at dalvik.system.NativeStart.main(Native Method)
W/InputMethodManagerService( 2206): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41971518 attribute=null
D/AndroidRuntime( 5277): 
D/AndroidRuntime( 5277): >>>>>> AndroidRuntime START com.android.internal.os.RuntimeInit <<<<<<
D/AndroidRuntime( 5277): CheckJNI is OFF
D/dalvikvm( 5277): Trying to load lib libjavacore.so 0x0
D/dalvikvm( 5277): Added shared lib libjavacore.so 0x0
D/dalvikvm( 5277): Trying to load lib libnativehelper.so 0x0
D/dalvikvm( 5277): Added shared lib libnativehelper.so 0x0
D/AndroidRuntime( 5277): Calling main entry com.android.commands.am.Am
D/AndroidRuntime( 5277): Shutting down VM
D/dalvikvm( 5277): GC_CONCURRENT freed 99K, 88% free 491K/4096K, paused 1ms+0ms, total 5ms

**Comment by vetruvet** [comment] 2012-08-13 12:08
Try RC4 when it is released in a bit, then tell me if it still won't reboot...

**Comment by Mushishi** [comment] 2012-08-13 12:31
Now reboot to recovery works again but it still write the wrong location for the recovery install script.

It still looks for the rom at the location /storage/sdcard0/OTA-Updater/download/"rom name" where it should just be /sdcard/OTA-Updater/download/"rom name" on the SGS3.

**Comment by vetruvet** [comment] 2012-08-13 12:38
actually, ROM Manager does the same thing (/storage/sdcard0)... it's really annoying, and i have to flash stuff my rebooting to recovery manually...

any chance that is on a jellybean ROM? i think that that is a new thing in jellybean to accomodate multiple sdcards/external storage/whatever...

anyway, original issue is fixed, so the issue is closed.

**Closed as completed by vetruvet** 2012-08-13 12:38 UTC

**Comment by vetruvet** [comment] 2012-08-13 12:42
on a side note, i think cwm recovery (or whoever else) have to fix it in their code, to detect multiple "sdcard" locations or external storage. However, i may just add a check for now to rewrite the location (e.g. "/storage/sdcard0/..." -> "/sdcard/..."

**Comment by Mushishi** [comment] 2012-08-13 12:44
Thanks... Well i think rom manager do that rewrite... Yes i am on a JB rom but even with the first CM10 alphas rom manager worked fine for auto install... :)

**Comment by vetruvet** [comment] 2012-08-13 12:48
hmmmm.... rom manager cannot auto install anything on the cm10 alpha rom i'm using (sensation)... so i think it's a bit rough right now...

**Comment by perettigiuliano** [comment] 2012-08-14 12:45
in the logcat above i see " java.lang.SecurityException: Neither user 10022 nor current process has android.permission.REBOOT" that is the same issue happening to me on the TF101.
What does it mean?

**Comment by Mushishi** [comment] 2012-08-14 13:07
perettigiuliano is that on RC3 or RC4.. Because it is fixed for me in RC4...

**Comment by perettigiuliano** [comment] 2012-08-14 13:33
the problem is not solved but covered by latest release, dev knows by email, maybe
